#!/bin/bash

set -ex

FFMPEG="/home/satoru/usr/bin/ffmpeg"
# FFMPEG="ffmpeg"
ASSDUMPER="assdumper"
ASSADJUST="assadjust"
ASS2VTT="ass-to-vtt"

TS_TYPE="general" # or "anime"

ENC_SIZE="720p" # or "1080p", "480p", "360p"
ENC_CODEC="h264"
ENC_CRF="24"

ENC_CODEC_A="-bsf:a aac_adtstoasc -c:a copy"

REC_START_OFFSET=8

enc_cmd="$FFMPEG"

OVERWRITE=0 # is default, 1 is force, 2 is no
NO_FFMPEG=0
NO_VTT=0

# parse options
while [ $# -gt 0 ] ; do
  case $1 in
    -s|--size)
      ENC_SIZE=$2
      shift 2
      ;;
    -c|--codec)
      ENC_CODEC=$2
      shift 2
      ;;
    -ca|--codec-audio)
      ENC_CODEC_A=$2
      shift 2
      ;;
    -t|--ts-type)
      TS_TYPE=$2
      shift 2
      ;;
    --force-encode-audio)
      BITRATE=$2
      ENC_CODEC_A="-c:a aac -ab $BITRATE"
      shift 2
      ;;
    --crf)
      ENC_CRF=$2
      shift 2
      ;;
    -p|--programid)
      MAP_FLAGS="-map 0:p:${2}:0 -map 0:p:${2}:1"
      shift 2
      ;;
    --map)
      MAP_FLAGS=$2
      shift 2
      ;;
    --multisounds)
      ENC_CODEC_A="-c:a aac -filter_complex '[0:1] channelsplit=channel_layout=stereo' -metadata:s:a:0 language=jpn -metadata:s:a:1 language=eng"
      shift
      ;;
    --start)
      REC_START_TIME=$2
      shift 2
      ;;
    --rec-start-offset) # parse rec start time from default chinachu filename format
      REC_START_OFFSET=$2
      shift 2
      ;;
    --start-in-name) # parse rec start time from default chinachu filename format
      REC_START_TIME=$(echo $(($(basename "$target_ts" | sed -e 's|\[[0-9]\{6\}-\([0-9]\{4\}\).*|\1|g'))) | sed -e "s|^\([0-9][0-9]\)\([0-9][0-9]\)$|\1:\2:$(( 60 - $REC_START_OFFSET ))|g")
      shift
      ;;
    -i|--input)
      target_ts=$2
      shift 2
      ;;
    --no-overwrite)
      OVERWRITE=2
      shift
      ;;
    --overwrite)
      OVERWRITE=1
      shift
      ;;
    --no-ffmpeg)
      NO_FFMPEG=1
      shift
      ;;
    --no-vtt)
      NO_VTT=1
      shift
      ;;
    *)
      echo "No such flag as $1"
      exit 1
      ;;
  esac
done

target_name="$(echo "$target_ts" | sed -e 's|.m2ts$||g')"


# =================
# process subtitles
# =================

if [ $NO_VTT -eq 0 ] ; then
  subtitle_dst="${target_name}.ass"

  $ASSDUMPER "$target_ts" > "${subtitle_dst}.nc"
  $ASSADJUST $REC_START_TIME "${subtitle_dst}.nc" > "$subtitle_dst"
  $ASS2VTT "$subtitle_dst" > "${target_name}.vtt"
  rm "${subtitle_dst}.nc"
fi


# =============
# convert movie
# =============

if [ $NO_FFMPEG -eq 0 ] ; then
  if [ -f "${target_name}.mp4" -a $OVERWRITE -eq 2 ] ; then
    echo "   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "
    echo "  !  Target file already exists  !"
    echo "   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "
    exit 2
  elif [ $OVERWRITE -eq 1 ] ; then
    enc_cmd="$enc_cmd -y"
  fi

  if [ $NO_VTT -eq 0 ] ; then
    case $ENC_CODEC in
      h264|h265)
        enc_cmd="$enc_cmd -i $target_ts -i $subtitle_dst $MAP_FLAGS -map 1:0 -c:s mov_text -metadata:s:2 language=jpn"
      ;;
    *)
      ;;
    esac
  else
    enc_cmd="$enc_cmd -i $target_ts $MAP_FLAGS"
  fi

  case $TS_TYPE in
    anime)
      enc_cmd="$enc_cmd -vf yadif=deint=interlaced,decimate,fieldmatch"
      case $ENC_CODEC in
        h264|h265)
          enc_cmd="$enc_cmd -tune animation"
          ;;
      esac
      ;;
    *)
      enc_cmd="$enc_cmd -vf yadif=deint=interlaced"
      ;;
  esac

  case $ENC_SIZE in
    360p)
      enc_cmd="$enc_cmd -s 640x360"
      ;;
    480p)
      enc_cmd="$enc_cmd -s 854x480"
      ;;
    720p)
      enc_cmd="$enc_cmd -s 1280x720"
      ;;
    1080p)
      ;;
  esac

  case $ENC_CODEC in
    h264)
      enc_cmd="$enc_cmd -c:v libx264 -preset medium -profile:v high -level 4.2 -x264-params crf=$ENC_CRF $ENC_CODEC_A -movflags +faststart"
      ;;
    h265)
      enc_cmd="$enc_cmd -c:v libx265 -preset medium -crf $ENC_CRF $ENC_CODEC_A -movflags +faststart"
      ;;
  esac

  case $ENC_CODEC in
    h264|h265)
      enc_cmd="$enc_cmd ${target_name}.mp4"
      ;;
    *)
      enc_cmd="$enc_cmd ${target_name}.mkv"
      ;;
  esac

  echo
  echo "$enc_cmd"
  echo

  $enc_cmd
fi
